package handlers

import (
	"log/slog"
	"net/http"

	"github.com/martinezsaweczko/whatsappBot-golang/http/middleware"
	httpSwagger "github.com/swaggo/http-swagger"

	// Generated swagger docs package.
	_ "github.com/martinezsaweczko/whatsappBot-golang/docs"
)

// SwaggerHandler serves the Swagger UI using the docs generated by swaggo.
type SwaggerHandler struct {
	basePath string
}

// NewSwaggerHandler creates a Swagger UI handler.
func NewSwaggerHandler(_ *slog.Logger, basePath string) *SwaggerHandler {
	return &SwaggerHandler{basePath: basePath}
}

// RegisterRoutes registers GET {basePath}/docs and GET {basePath}/docs/*.
func (h *SwaggerHandler) RegisterRoutes(router Router, middlewares ...middleware.Middleware) {
	path := h.basePath + "/docs"
	swaggerHandler := httpSwagger.Handler(
		httpSwagger.URL(h.basePath + "/docs/doc.json"),
	)

	register := func(pattern string, handler http.Handler) {
		if len(middlewares) > 0 {
			router.HandleWithMiddleware(pattern, handler, middlewares...)
		} else {
			router.Handle(pattern, handler)
		}
	}

	register(path, http.RedirectHandler(path+"/", http.StatusMovedPermanently))
	register(path+"/", swaggerHandler)
}
