-- +goose Up
CREATE TABLE IF NOT EXISTS subscriptions (
    id BINARY(16) PRIMARY KEY,
    subscription_text VARCHAR(255),
    user VARCHAR(255),
    created_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS jwt_used (
    id BINARY(16) PRIMARY KEY,
    jwt VARCHAR(512),
    created_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX jwt_index (jwt)
);

CREATE TABLE IF NOT EXISTS file_usage (
    id BINARY(16) PRIMARY KEY,
    file VARCHAR(255),
    result VARCHAR(50),
    created_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_usage (
    id BINARY(16) PRIMARY KEY,
    user VARCHAR(255),
    file VARCHAR(255),
    created_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- +goose Down
DROP TABLE IF EXISTS subscriptions;
DROP TABLE IF EXISTS jwt_used;
DROP TABLE IF EXISTS file_usage;
DROP TABLE IF EXISTS user_usage;
